In [3]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

In [86]:
# NumPy routines which allocate memory and fill arrays with value and accept shape as input argument
# creating a 1-d vector of zeros
a = np.zeros(4);                
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# accepts shape as input argument
a = np.zeros((4,3));      
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# create a 3d array 
a = np.zeros((2,3,4));      
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# creating a vector with 4 random elements
a = np.random.random_sample(4); 
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [0. 0. 0. 0.]
a shape = (4,)

a = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
a shape = (4, 3)

a = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
a shape = (2, 3, 4)

a = [0.40563692 0.09476425 0.14356247 0.87466436]
a shape = (4,)


In [107]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(5.);              
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.random.rand(4);         
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [0. 1. 2. 3. 4.]
a shape = (5,)

a = [0.13701599 0.57725127 0.1457312  0.06924033]
a shape = (4,)


In [96]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);     #int
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.array([5.,4,3,2]);  #float
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [5 4 3 2]
a shape = (4,)

a = [5. 4. 3. 2.]
a shape = (4,)


## indexing

In [123]:
#### vector indexing operations on 1-D vectors
a = np.arange(10)
print(f"a = {a}")

#access an element
print(f"a[2]  = {a[2]}")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

a = [0 1 2 3 4 5 6 7 8 9]
a[2]  = 2
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10
