In [3]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

In [86]:
# NumPy routines which allocate memory and fill arrays with value and accept shape as input argument
# creating a 1-d vector of zeros
a = np.zeros(4);                
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# accepts shape as input argument
a = np.zeros((4,3));      
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# create a 3d array 
a = np.zeros((2,3,4));      
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

# creating a vector with 4 random elements
a = np.random.random_sample(4); 
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [0. 0. 0. 0.]
a shape = (4,)

a = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
a shape = (4, 3)

a = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
a shape = (2, 3, 4)

a = [0.40563692 0.09476425 0.14356247 0.87466436]
a shape = (4,)


In [107]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(5.);              
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.random.rand(4);         
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [0. 1. 2. 3. 4.]
a shape = (5,)

a = [0.13701599 0.57725127 0.1457312  0.06924033]
a shape = (4,)


In [96]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);     #int
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.array([5.,4,3,2]);  #float
print(f"a = {a}")
print(f"a shape = {a.shape}")

a = [5 4 3 2]
a shape = (4,)

a = [5. 4. 3. 2.]
a shape = (4,)


## indexing

In [123]:
#### vector indexing operations on 1-D vectors
a = np.arange(10)
print(f"a = {a}")

#access an element
print(f"a[2]  = {a[2]}")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

a = [0 1 2 3 4 5 6 7 8 9]
a[2]  = 2
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


## slicing

In [131]:
#vector slicing operations
a = np.arange(10)
print(f"a = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];    
print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];    
print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        
print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        
print("a[:3]    = ", c)

# access all elements
c = a[:];        
print("a[:]     = ", c)

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


## single vector operations

In [145]:
a = np.array([1,2,3,4])
print(f"a = {a}")

# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

a = [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]
b = 5 * a : [ 5 10 15 20]


## multi vector operations

In [141]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"adding corresponding elements of a & b:  {a + b}")

adding corresponding elements of a & b:  [0 0 6 8]


In [143]:
#doesnt work if arrays have different size
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


## vector dot product 

In [152]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [154]:
# dot product of vector a, b using our method
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [162]:
# dot product of vector a, b using np.dot() method
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}") 

c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}")


NumPy 1-D np.dot(a, b) = 24
NumPy 1-D np.dot(b, a) = 24


## comparing speed

In [170]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms \n")


tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 7.1239 ms 

my_dot(a, b) =  2501072.5817
loop version duration: 3097.2209 ms 


In [176]:
X = np.array([[1],[2],[3],[4]])    # 2d array 
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


## matrices (2d array)

In [189]:
a = np.zeros((1, 5))                                       
print(f"a = {a}")
print(f"a shape = {a.shape}\n")                   

a = np.zeros((2, 1))                                                                   
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.random.random_sample((1, 1))  
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = [[0. 0. 0. 0. 0.]]
a shape = (1, 5)

a = [[0.]
 [0.]]
a shape = (2, 1)

a = [[0.53516563]]
a shape = (1, 1)



In [193]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);  
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

a = [[5]
 [4]
 [3]]
a shape = (3, 1)

a = [[5]
 [4]
 [3]]
a shape = (3, 1)



## indexing

In [216]:
#vector indexing operations on matrices
#reshape is a convenient way to create matrices
#The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.
# here the argument 2 tells num of columns
a = np.arange(6).reshape(-1, 2)   
print(f"a = {a}")
print(f"a shape = {a.shape}\n")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]}")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}")

a = [[0 1]
 [2 3]
 [4 5]]
a shape = (3, 2)


a[2,0].shape:   (), a[2,0] = 4
a[2].shape:   (2,), a[2]   = [4 5]


## Slicing

In [233]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}\n")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array\n")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array\n")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("\na[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array\n")

# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array\n")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array

a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)

a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array

a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array

